version: "3.9"

services:
  api:
    build: .
    container_name: clients-api
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/clients_db
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: clients_db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
